[package]
name = "ordinal-map"
version = "0.1.0"
edition = "2021"

[dependencies]
ordinal-map-derive = { path = "../ordinal-map-derive", version = "=0.1.0" }

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
